name: Build Resume PDF 

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]	

jobs:
  build:		
    runs-on:  ubuntu-latest		
    steps:
    - name:  Checkout code		 
      uses:  actions/checkout@v3
    

    - name:  Build Docker image
      run:  docker build --tag my_resume .


    - name:  Run container and build PDF
      run:  docker run --name resume_build my_resume

		
    - name:  Copy PDF from container 
     run:  docker cp resume_build:/resume/CV/main.pdf ./main.pdf


    - name:	Upload PDF as artifact 
     uses:  actions/upload-artifact@v3
     with:
       name:	resume-pdf
       path:	main.pdf 
		      